services:
  cloudflared:
    container_name: cloudflare-tunnel-myfamilylibrary
    image: cloudflare/cloudflared:latest
    network_mode: "host"
    # command: tunnel --no-autoupdate --hostname myfamilylibrary.org --url https://127.0.0.1:80
    command: tunnel --no-autoupdate run myfamilylibrary
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: unless-stopped