services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${S3_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${S3_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - s3_data:/data
    command: server /data --console-address ":9001"
    # To troubleshoot minio, exec into the minio container and run: 
    # mc alias set myminio http://127.0.0.1:9000
    # mc admin user -v -a myminio THEN enter ${S3_ROOT_USER} ${S3_ROOT_PASSWORD}

  createbuckets:
    image: minio/mc
    container_name: initialize_minio
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${S3_ROOT_USER} ${S3_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/${S3_USER_UPLOADS_BUCKET};
      /usr/bin/mc admin user add myminio ${S3_USER_UPLOADS_ACCESS_KEY} ${S3_USER_UPLOADS_SECRET_KEY};
      /usr/bin/mc admin policy attach myminio readwrite --user ${S3_USER_UPLOADS_ACCESS_KEY};
      exit 0;
      "

volumes:
  s3_data: