services:
  tailscale-sidecar:
    image: tailscale/tailscale:latest
    container_name: tailscale-sidecar
    # MUST use network_mode: "host" to see the 'web' service
    network_mode: "host"
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      # Named volume to persist Tailscale state (IP, keys, etc.)
      - tailscale_state:/var/lib/tailscale
      - /var/run/tailscale:/var/run/tailscale
    environment:
      # *** REQUIRED: Replace this with your actual Tailscale Auth Key ***
      TS_AUTH_KEY: ${TS_AUTH_KEY}
      # Forces the container to use userspace networking mode
      TS_USERSPACE: "true"
      # Optional: Set a recognizable hostname for the node
      TS_HOSTNAME: ${TS_HOST_NAME}
    
    # This command funnels traffic to 127.0.0.1:{APP_PORT}
    # Because both containers are in "host" mode, 127.0.0.1
    # is the host's loopback address, where 'web' is listening.
    command: |
      sh -c "
        tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/var/run/tailscale/tailscaled.sock &

        # Give it a few seconds just to be safe
        sleep 5

        tailscale --socket=/var/run/tailscale/tailscaled.sock up --authkey=${TS_AUTH_KEY} --hostname=${TS_HOST_NAME} --accept-routes=false

        tailscale --socket=/var/run/tailscale/tailscaled.sock funnel ${APP_PORT}
      "
    restart: unless-stopped

volumes:
  tailscale_state: {}
