services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: vm-django
    network_mode: "host"  # Required for Funnel and Serve on port 443
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    environment:
      - TS_AUTH_KEY=${TS_AUTH_KEY}
      - APP_PORT=${APP_PORT}  # Match your Django app port
    volumes:
      - /var/lib/tailscale:/var/lib/tailscale   # Persistent state
      - /var/run/tailscale:/var/run/tailscale   # Socket path
    devices:
      - /dev/net/tun:/dev/net/tun
    command: |
      sh -c '
        echo "🧹 Cleaning old socket (if any)..."
        rm -f /var/run/tailscale/tailscaled.sock

        echo "🚀 Starting tailscaled..."
        tailscaled --state=/var/lib/tailscale/tailscaled.state \
                   --socket=/var/run/tailscale/tailscaled.sock &

        # Wait for the daemon to be ready
        until [ -S /var/run/tailscale/tailscaled.sock ]; do
          echo "⌛ Waiting for tailscaled..."
          sleep 1
        done

        echo "🔐 Bringing up Tailscale..."
        tailscale --socket=/var/run/tailscale/tailscaled.sock up \
                  --auth-key=${TS_AUTH_KEY} \
                  --hostname=vm-django \
                  --ssh=false

        echo "🌐 Configuring Serve for Django app on port ${APP_PORT}..."
        tailscale --socket=/var/run/tailscale/tailscaled.sock serve --https=443 http://127.0.0.1:${APP_PORT}

        echo "🌍 Enabling Funnel..."
        tailscale --socket=/var/run/tailscale/tailscaled.sock funnel on

        echo "✅ Tailscale is up and serving via Funnel!"
        tailscale --socket=/var/run/tailscale/tailscaled.sock serve status
        tailscale --socket=/var/run/tailscale/tailscaled.sock funnel status

        # Keep container running
        tail -f /dev/null
      '



# services:
#   tailscale:
#     # image: tailscale/tailscale:latest
#     image: tailscale/tailscale:v1.66.3
#     hostname: vm-django # Replace with your desired hostname
#     volumes:
#       - /var/lib/tailscale:/var/lib/tailscale # Persist Tailscale state
#       - /dev/net/tun:/dev/net/tun # Required for Tailscale to function
#     cap_add:
#       - NET_ADMIN # Required for network configuration
#       - SYS_ADMIN # Required for network configuration
#     environment:
#       - TS_AUTHKEY=${TS_AUTH_KEY} # Replace with your generated auth key
#       - TS_ACCEPT_ROUTES=true # If you want to accept advertised routes
#       - TS_ADVERTISE_ROUTES=192.168.1.2/32 # Example: advertise your local network subnet
#       - TS_USERSPACE=false # Run tailscaled in kernel mode (recommended)
#       - TS_FUNNEL=true # Enable Tailscale Funnel for this node
#       - TS_EXTRA_ARGS=--funnel ${APP_PORT} # Example: specify additional arguments
#       # - TS_ROUTES=192.168.1.2/32 # Example: specify routes to advertise
#     restart: unless-stopped
#     network_mode: "host" # Use host networking 


# services:
#   tailscale:
#     image: tailscale/tailscale:latest
#     container_name: tailscale
#     hostname: vm-django
#     network_mode: "host"  # required for funnel to bind to your app port
#     restart: unless-stopped
#     cap_add:
#       - NET_ADMIN
#       - SYS_ADMIN
#     environment:
#       - TS_AUTHKEY=${TS_AUTH_KEY}
#       - APP_PORT=${APP_PORT}  # change this to match your Django port
#     volumes:
#       - /var/lib/tailscale:/var/lib/tailscale   # persistent state
#       - /var/run/tailscale:/var/run/tailscale   # socket path
#     command: |
#       sh -c '
#         # Clean up old socket if it exists
#         rm -f /var/run/tailscale/tailscaled.sock

#         # Start the Tailscale daemon in userspace networking mode
#         tailscaled --tun=userspace-networking \
#                    --socks5-server=localhost:1055 \
#                    --state=/var/lib/tailscale/tailscaled.state \
#                    --socket=/var/run/tailscale/tailscaled.sock &

#         # Wait for the socket to appear
#         until [ -S /var/run/tailscale/tailscaled.sock ]; do echo "waiting for tailscaled..."; sleep 1; done

#         # Bring up Tailscale
#         tailscale --socket=/var/run/tailscale/tailscaled.sock up \
#                   --auth-key=${TS_AUTH_KEY} \
#                   --hostname=vm-django \
#                   --ssh=false

#         # Serve the local Django app over HTTPS within the tailnet
#         tailscale --socket=/var/run/tailscale/tailscaled.sock serve --https=443 http://127.0.0.1:${APP_PORT}

#         # Optional: enable Funnel for public exposure (if you’ve enabled it in admin panel)
#         tailscale --socket=/var/run/tailscale/tailscaled.sock funnel on

#         # Keep container alive
#         tail -f /dev/null
#       '
